spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
  name: moviefun
logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: <access key id>
  secretKey: <secret access key>
  bucketName: <name of the bucket>

security:
  basic:
    enabled: false
